ArrowDirectorDistance: 50
ArrowDirectorRange: 120
ArrowVelocity: 5
ArrowDamage: 10
DamageCooldown: false
Converge: true
ConvergenceDistance: 180.0
ArrowDirectorsAllowed:
- Airskiff
- Airship
